remote_theme: pages-themes/cayman@v0.2.0 # https://github.com/pages-themes/cayman
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: XMas OneShot 2022
description: Kaer Maga, Stadt der Fremden
show_downloads: false
baseurl: /
